version: '3'

services:

  mysql:
    image: mysql:5.7
    ports: 
    - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: docker
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks: 
    - java-mysql

  java:
    image: java-maven
    restart: on-failure
    build: .
    ports: 
    - 8080:8080
    environment: 
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: admin
      DATABASE_NAME: docker
      DATABASE_PORT: 3306
    depends_on: 
    - mysql
    networks: 
    - java-mysql

networks: 
  java-mysql:
